import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/assets/css/globals.css";
import StoreProvider from "@/lib/StoreProvider";
import LayoutNav from "./components/layout/LayoutNav";

const font = Open_Sans({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "NewsStand",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>
                <StoreProvider>
                    <LayoutNav />
                    {children}
                </StoreProvider>
            </body>
        </html>
    );
}
